### ISSUE TITLE
8bitdo Retro Receiver locks up the system.

### ISSUE THREAD

**Issue by terenceang** [UzixLS/zx-sizif-512#9] opened 2022-01-20 14:57 UTC
https://www.8bitdo.com/retro-receiver-genesis-mega-drive/

Test the Sizif 512K with a Retro Reciever for SEGA MegaDrive crashes and locks up the system. I need to turn the machine on and off to get it back.

**Comment by UzixLS** [comment] 2022-01-20 15:12
Is 3.3V power line stable?

**Comment by UzixLS** [comment] 2022-01-20 15:15
I think this RF dongle maybe drawing too much power. I would buy one for tests probably.

**Comment by terenceang** [comment] 2022-01-20 17:50
where in the world are you located? I can order 1 and have it shipped to you. 
It can literally work with any BT controller. 
https://download.8bitdo.com/Manual/Receiver/md/MD_RR_ENG_Manual.pdf

**Comment by UzixLS** [comment] 2022-01-20 20:06
This isn't required.

After googling a bit, I found complaints about the compatibility of 8bitdo controllers with zx-uno:
https://www.zxuno.com/forum/viewtopic.php?t=3972

This may be caused by the same reason - zx uno like sizif provides only 3.3V power for gamepad.

**Comment by terenceang** [comment] 2022-01-21 02:09
I tried powering it through USB, it didn’t crash the system when you plug it in and crashes intermittently.
It will be nice if it works, i will order the 2.4Ghz ver to try out. Thanks

**Comment by terenceang** [comment] 2022-01-21 02:12
Anyway, I would love to send 1 to you if you want to work on it, at least to thank you for the hard work and wonderful design.

**Comment by UzixLS** [comment] 2022-03-20 10:12
I bought 8BitDo M30 gamepad with Megadrive Bluetooth receiver and it's works just flawlessly with Sizif-512 (rev.D). So I assume there is some issue with your hardware.

**Comment by UzixLS** [comment] 2022-10-05 05:42
PCB rev.E released with +5 power for gamepad. This should eliminate any theoretical incompatibilities.

**Closed by UzixLS** 2022-10-05 05:42 UTC
